### ISSUE TITLE
Error handle in Auth flow

### ISSUE THREAD

**Issue by ludoded** [Radiksidenko/social_network_IOS#3]
For now it's not showing error when user is typing wrong input.
When I sign up with invalid email, it still pass to Main view. Instead it should show error

Show errors now with (https://developer.apple.com/documentation/uikit/uialertcontroller)[UIAlertController]

- [x] Show error when wrong input is typed for Sign In, Sign up, Forget password
- [x] Show error when request from Firebase responds with error and don't show main scene

**Comment by Radiksidenko** [comment]
@ludoded I have done it .
