### ISSUE TITLE
Show spinner while waiting for response from Firebase

### ISSUE THREAD

**Issue by ludoded** [Radiksidenko/social_network_IOS#4]
As a user I want to see spinner while waiting a response from server

- [x] Show spinner when I hit the Sign Up/ Sign In/ Forget Password button
- [x] Hide spinner when you get an error or successful response from server

You can see how it can be implemented (http://brainwashinc.com/2017/07/21/loading-activity-indicator-ios-swift/)[here]

Keep in mind that showing/hiding of the spinner should be done on main thread.

**Comment by Radiksidenko** [comment]
@ludoded I have done it .
